### ISSUE TITLE
Contact

### ISSUE THREAD

**Issue by erykjj** [chessurisme/playground#5]
Hi Kyle,

Just wanted to let you know that I've added another (hopefully useful) publication to my [JWPubLib](https://github.com/erykjj/jwpublib).

Thank you again for the Cebuano & Tagalog translations for BRS! There have been many downloads :-)

Also, feel free to post a reference to these jwpubs on jwtalk.net. I believe you have an account. Thanks.

Eryk

**Comment by chessurisme** [comment]
Hey Eryk,

Nice to meet you again. Your project is quite interesting. I'm pleased to collaborate with you again. Any repo can I fork?

Yes, I am in JWTalk. There's someone in there that I just chatted few months ago, I thought that it was you. The name and the address is same as yours. I can't verify if it was you, but please let me know if I got touched with you there. 😁

Sincerely yours,
Kyle

**Comment by erykjj** [comment]
No, we did not chat on JWTalk; I don't have an account there. It was just on Github... "Vine's" Hebrew dictionary. Remember? :-)

**Comment by chessurisme** [comment]
> "Vine's" Hebrew dictionary. Remember? :-)

Yeah, I do remember you very much. I just followed you here, that is why I can't forget you. 
Oh, I send a wrong message to a wrong brother, but don't worry, he doesn't reply me. But how did you know that I was in JWTalk?

Regarding on the translation of the new publication, is ther any array of strings or object or JSON can I refer, or perhaps a repo to fork? Let me know. The publication is interesting, I already downloaded the English version, it was quite nice.

**Comment by erykjj** [comment]
No there is nothing to translate for this one. It'll be in English only.

**Comment by chessurisme** [comment]
It would be nice, if you added a translation to this. I'll spare my time for this.

**Comment by erykjj** [comment]
The problem is, the source data (from si, and the indexes) has to be obtained and parsed in each language. It's complicated. Sorry.

**Comment by chessurisme** [comment]
> The problem is, the source data (from si, and the indexes) has to be obtained and parsed in each language. It's complicated. Sorry.

I understand whenever someone try to suggest a feature in our own programs, our mind starts to mutate and if it is fine, it will be added, but if it fail we say sorry. XD Any project can I collab?

**Comment by erykjj** [comment]
Feel free to delete this issue ;-)

**Comment by chessurisme** [comment]
Thanks for the chat, Eryk. Let me know if I can help in some ways. 
Are you open in code reviews? I want to learn more about your ways.

**Comment by erykjj** [comment]
Yes, I believe it's open for pull requests.

**Comment by chessurisme** [comment]
That's great to hear! I'm really excited about this opportunity to learn from you. I've got a current project I've been working on, and I'd love to get your insights through a code review. Whenever you have some time, could we set up a time to go over it together? Looking forward to the collaboration!

BTW, I'll want to tell anyone in JWTalk about your new publication, I'll tell you everything about it.

**Comment by chessurisme** [comment]
Already added, check this one out: https://jwtalk.net/topic/56961-timeline-of-bible-history-jwpub/

**Comment by erykjj** [comment]
> That's great to hear! I'm really excited about this opportunity to learn from you. I've got a current project I've been working on, and I'd love to get your insights through a code review. Whenever you have some time, could we set up a time to go over it together? Looking forward to the collaboration!
> 
You can create a private repo and invite me as a collaborator - like I did before. We can discuss stuff there ;-)

**Comment by chessurisme** [comment]
> > That's great to hear! I'm really excited about this opportunity to learn from you. I've got a current project I've been working on, and I'd love to get your insights through a code review. Whenever you have some time, could we set up a time to go over it together? Looking forward to the collaboration!
> 
> You can create a private repo and invite me as a collaborator - like I did before. We can discuss stuff there ;-)

Should be in the project repo or same as yours before (only for contact)?

**Comment by chessurisme** [comment]
Check the [forum](https://jwtalk.net/topic/56961-timeline-of-bible-history-jwpub/) everyone is interested.

**Comment by chessurisme** [comment]
> > Should be in the project repo or same as yours before (only for contact)?
> 
> Up to you. Is your project public? It could be a private repo just for communication.

I'm going to private my repo and add you there. Wait for it, I'm going to set up it first and add you there.

**Comment by erykjj** [comment]
> Check the [forum](https://jwtalk.net/topic/56961-timeline-of-bible-history-jwpub/) everyone is interested.

Kyle, I noticed at least one person talking about adding notes in this jwpub. This may be problematic, so I've added this note in the README:
`Keep in mind that notes and highlights are linked to paragraph numbers, so if you annotate in any way and a future release includes additional historical events (paragraphs), your notes and highlights will no longer match up.`

You may want to add that in your thread there ;-)

**Comment by chessurisme** [comment]
Hi, Eric.

This is my framework of my planned code project, this is just a simple web app that manage attendance during meetings. How is it?

![diagram-export-1-9-2024-3_30_48-PM](https://github.com/chessurisme/playground/assets/137697011/81ec5a92-cc8b-4535-ae2c-f6cb9802c1db)

I am going to add other feature soon like exporting, importing data, and whatsnot. Does this one going to be a good start? Your review helps me to learn from you, I know you are experienced in programming.

**Comment by erykjj** [comment]
Hi Kyle,
I thought we were going to move to a private repo/chat
